"""Calibrate a geometric temperature schedule from sampled loss changes."""

import math
import statistics
from collections.abc import Callable

from .datamodel import Solution, TemperatureConfig
from .utils import FALLBACK_DELTA_MAGNITUDE, MIN_DELTA_MAGNITUDE

# Acceptance probabilities for the typical delta sampled around the initial solution.
INITIAL_REFERENCE_ACCEPTANCE_PROBABILITY = 0.8
FINAL_REFERENCE_ACCEPTANCE_PROBABILITY = 1e-12
MAX_CALIBRATION_SAMPLES = 100


def calibrate_temperature(
    solution: Solution,
    steps: int,
    sample_candidate: Callable[[Solution], Solution | None],
) -> TemperatureConfig:
    """Choose temperatures using candidates generated by the solver."""
    if steps <= 0:
        raise ValueError("steps must be positive")
    samples = min(MAX_CALIBRATION_SAMPLES, max(1, steps // 10))
    typical_delta = _estimate_typical_loss_delta(solution, samples, sample_candidate)
    initial = -typical_delta / math.log(INITIAL_REFERENCE_ACCEPTANCE_PROBABILITY)
    final = -typical_delta / math.log(FINAL_REFERENCE_ACCEPTANCE_PROBABILITY)
    cooling_rate = (final / initial) ** (1 / max(steps - 1, 1))
    return TemperatureConfig(initial, final, cooling_rate)


def _estimate_typical_loss_delta(
    solution: Solution,
    samples: int,
    sample_candidate: Callable[[Solution], Solution | None],
) -> float:
    """Estimate median significant absolute loss changes around one solution.

    Changes at or below MIN_DELTA_MAGNITUDE are ignored. If no significant
    changes are observed, return FALLBACK_DELTA_MAGNITUDE.
    """
    if samples <= 0:
        raise ValueError("samples must be positive")

    deltas = []
    for _ in range(samples):
        candidate = sample_candidate(solution)
        if candidate is None:
            continue
        delta = abs(candidate.loss - solution.loss)
        if not math.isfinite(delta):
            raise ValueError("Non-finite loss delta")
        if delta > MIN_DELTA_MAGNITUDE:
            deltas.append(delta)
    return statistics.median(deltas) if deltas else FALLBACK_DELTA_MAGNITUDE
